/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ConsultantsRouteImport } from './routes/consultants'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PortalRequirementsRouteImport } from './routes/portal.requirements'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalHelpRouteImport } from './routes/portal.help'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as PortalSubmissionsNewRouteImport } from './routes/portal.submissions.new'
import { Route as PortalProjectsIdRouteImport } from './routes/portal.projects.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsRoute = ConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortalRequirementsRoute = PortalRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelpRoute = PortalHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PortalRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const PortalSubmissionsNewRoute = PortalSubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsIdRoute = PortalProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/portal': typeof PortalIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/consultants'
    | '/notifications'
    | '/portal'
    | '/projects'
    | '/reports'
    | '/tasks'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/projects'
    | '/portal/requirements'
    | '/projects/$id'
    | '/portal/'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/consultants'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/tasks'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/projects'
    | '/portal/requirements'
    | '/projects/$id'
    | '/portal'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/consultants'
    | '/notifications'
    | '/portal'
    | '/projects'
    | '/reports'
    | '/tasks'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/projects'
    | '/portal/requirements'
    | '/projects/$id'
    | '/portal/'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ConsultantsRoute: typeof ConsultantsRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants': {
      id: '/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof ConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portal/requirements': {
      id: '/portal/requirements'
      path: '/requirements'
      fullPath: '/portal/requirements'
      preLoaderRoute: typeof PortalRequirementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/help': {
      id: '/portal/help'
      path: '/help'
      fullPath: '/portal/help'
      preLoaderRoute: typeof PortalHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/portal/submissions/new': {
      id: '/portal/submissions/new'
      path: '/submissions/new'
      fullPath: '/portal/submissions/new'
      preLoaderRoute: typeof PortalSubmissionsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects/$id': {
      id: '/portal/projects/$id'
      path: '/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof PortalProjectsIdRouteImport
      parentRoute: typeof PortalProjectsRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface PortalProjectsRouteChildren {
  PortalProjectsIdRoute: typeof PortalProjectsIdRoute
}

const PortalProjectsRouteChildren: PortalProjectsRouteChildren = {
  PortalProjectsIdRoute: PortalProjectsIdRoute,
}

const PortalProjectsRouteWithChildren = PortalProjectsRoute._addFileChildren(
  PortalProjectsRouteChildren,
)

interface PortalRouteChildren {
  PortalHelpRoute: typeof PortalHelpRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProjectsRoute: typeof PortalProjectsRouteWithChildren
  PortalRequirementsRoute: typeof PortalRequirementsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalSubmissionsNewRoute: typeof PortalSubmissionsNewRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalHelpRoute: PortalHelpRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProjectsRoute: PortalProjectsRouteWithChildren,
  PortalRequirementsRoute: PortalRequirementsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalSubmissionsNewRoute: PortalSubmissionsNewRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ConsultantsRoute: ConsultantsRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
