/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ConsultantsRouteImport } from './routes/consultants'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PortalRequirementsRouteImport } from './routes/portal.requirements'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalHelpRouteImport } from './routes/portal.help'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as PortalProjectsIndexRouteImport } from './routes/portal.projects.index'
import { Route as PortalSubmissionsNewRouteImport } from './routes/portal.submissions.new'
import { Route as PortalProjectsIdRouteImport } from './routes/portal.projects.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsRoute = ConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRequirementsRoute = PortalRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelpRoute = PortalHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PortalRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const PortalProjectsIndexRoute = PortalProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSubmissionsNewRoute = PortalSubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsIdRoute = PortalProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
  '/portal/projects': typeof PortalProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/consultants': typeof ConsultantsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/requirements': typeof PortalRequirementsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/submissions/new': typeof PortalSubmissionsNewRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/companies'
    | '/consultants'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/portal'
    | '/register'
    | '/reports'
    | '/tasks'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/requirements'
    | '/projects/$id'
    | '/admin/'
    | '/portal/'
    | '/projects/'
    | '/requests/'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
    | '/portal/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companies'
    | '/consultants'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reports'
    | '/tasks'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/requirements'
    | '/projects/$id'
    | '/admin'
    | '/portal'
    | '/projects'
    | '/requests'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
    | '/portal/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/companies'
    | '/consultants'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/portal'
    | '/register'
    | '/reports'
    | '/tasks'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/companies/$id'
    | '/portal/help'
    | '/portal/notifications'
    | '/portal/requirements'
    | '/projects/$id'
    | '/admin/'
    | '/portal/'
    | '/projects/'
    | '/requests/'
    | '/portal/projects/$id'
    | '/portal/submissions/new'
    | '/portal/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ConsultantsRoute: typeof ConsultantsRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants': {
      id: '/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof ConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/requirements': {
      id: '/portal/requirements'
      path: '/requirements'
      fullPath: '/portal/requirements'
      preLoaderRoute: typeof PortalRequirementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/help': {
      id: '/portal/help'
      path: '/help'
      fullPath: '/portal/help'
      preLoaderRoute: typeof PortalHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/projects/': {
      id: '/portal/projects/'
      path: '/projects'
      fullPath: '/portal/projects/'
      preLoaderRoute: typeof PortalProjectsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/submissions/new': {
      id: '/portal/submissions/new'
      path: '/submissions/new'
      fullPath: '/portal/submissions/new'
      preLoaderRoute: typeof PortalSubmissionsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects/$id': {
      id: '/portal/projects/$id'
      path: '/projects/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof PortalProjectsIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface PortalRouteChildren {
  PortalHelpRoute: typeof PortalHelpRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalRequirementsRoute: typeof PortalRequirementsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalProjectsIdRoute: typeof PortalProjectsIdRoute
  PortalSubmissionsNewRoute: typeof PortalSubmissionsNewRoute
  PortalProjectsIndexRoute: typeof PortalProjectsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalHelpRoute: PortalHelpRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalRequirementsRoute: PortalRequirementsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalProjectsIdRoute: PortalProjectsIdRoute,
  PortalSubmissionsNewRoute: PortalSubmissionsNewRoute,
  PortalProjectsIndexRoute: PortalProjectsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ConsultantsRoute: ConsultantsRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
